# Generated by Django 5.1 on 2024-08-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Saldo'),
        ),
    ]
