# Generated by Django 5.1 on 2024-08-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0002_alter_conta_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='descricao',
            field=models.TextField(max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='nome',
            field=models.CharField(error_messages='Dê um nome para a conta', max_length=100, verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo financeiro da conta em Reais(R$)', max_digits=9, verbose_name='Saldo em R$'),
        ),
    ]
